baseurl = "/"
languageCode = "en-us"
title = "Cytoverse"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Installation"
    url = "/install"
    weight = -10
[[menu.main]]
    name = "Learn"
    url = "/learn"
    weight = -9
[[menu.main]]
    name = "Blog"
    url = "/post"
    weight = -8
[[menu.main]]
    name = "Help"
    url = "/help"
    weight = -7
[[menu.main]]
    name = "Citation"
    url = "/citation"
    weight = -6
[[menu.main]]
    name = "Github"
    url = "https://github.com/RGLab/cytoverse"
    weight = -4

[params]
    description = "A collection of tools for analysis of cytometry data"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "img/cytoverse_logo.png"
    width = "100rem"
    height = "100rem"
    alt = "Logo"
    
    [params.icons]
        [params.icons.fh]
        url = "img/FH_logo.png"
        alt = "RGLab Website"
        [params.icons.github]
        url = "img/github_logo.png"
        alt = "RGLab GitHub"
    

